

spring:
  application:
    name: sorce-share-api-gateway
    description: A Gateway to handle all routing part
    version: 0.0.1

server:
  port: 10010

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

routes:
  userStore:
    url:
      signUp: lb://USER-STORE-API/api/auth/signUp
      signIn: lb://USER-STORE-API/api/auth/signIn